### ISSUE TITLE
Make generic, remove core::arch::x86_64?

### ISSUE THREAD

**Issue by kyclark** [mpetri/rmq-rs#1]
Any chance you'd be willing to remove the dependency on core::arch::x86_64 to make this work on ARM? @mpetri

**Comment by kyclark** [comment]
Actually, it seems you have a wrapper `select1_in_u64` function to determine whether to run `select1_in_u64_slow` or `select1_in_u64_bmi2` when `target_feature = "bmi2"`, but this is not detected on ARM. Maybe it's a simple fix there?

**Comment by mpetri** [comment]
Can you provide a CR

**Comment by mpetri** [comment]
I released version 0.2 where this now should conditionally use bmi2 if available.

**Comment by kyclark** [comment]
Yes, it compiles on macOS! Thanks very much.
